# Generated by Django 4.2 on 2026-04-10 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('subject', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('is_reviewed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'سوال پرتکرار',
                'verbose_name_plural': 'سوالات پرتکرار',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name_fa', models.CharField(default='فارال یار', max_length=120)),
                ('site_name_en', models.CharField(default='FaralYar', max_length=120)),
                ('tagline', models.CharField(default='دستیار هوش مصنوعی تیم فارال', max_length=240)),
                ('hero_title', models.CharField(default='دستیار هوش مصنوعی فارسی برای تیم\u200cها و کاربران حرفه\u200cای', max_length=240)),
                ('hero_subtitle', models.TextField(default='FaralYar محیطی مدرن برای گفتگو با مدل\u200cهای مختلف هوش مصنوعی، مدیریت اشتراک، محتوای آموزشی و تجربه\u200cای روان روی موبایل و دسکتاپ است.')),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=32)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('telegram_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('x_url', models.URLField(blank=True)),
                ('light_logo', models.CharField(default='branding/faralyar-main.png', max_length=255)),
                ('dark_logo', models.CharField(default='branding/farayarl-white.png', max_length=255)),
                ('mono_dark_logo', models.CharField(default='branding/faralyar-black.png', max_length=255)),
                ('mono_light_logo', models.CharField(default='branding/farayarl-white.png', max_length=255)),
                ('green_logo', models.CharField(default='branding/faralyar-green.png', max_length=255)),
                ('blue_logo', models.CharField(default='branding/faralyar-blue.png', max_length=255)),
                ('primary_color', models.CharField(default='#28ab88', max_length=7)),
                ('secondary_color', models.CharField(default='#013366', max_length=7)),
                ('otp_provider_name', models.CharField(blank=True, max_length=80)),
                ('otp_provider_api_key', models.CharField(blank=True, max_length=255)),
                ('otp_provider_sender', models.CharField(blank=True, max_length=120)),
                ('zarinpal_merchant_id', models.CharField(blank=True, max_length=255)),
                ('zarinpal_sandbox', models.BooleanField(default=True)),
                ('payment_guide_text', models.TextField(blank=True)),
                ('payment_guide_url', models.URLField(blank=True)),
                ('free_guest_message_limit', models.PositiveSmallIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_key', models.CharField(choices=[('home', 'خانه'), ('about', 'درباره ما'), ('contact', 'تماس'), ('terms', 'قوانین'), ('privacy', 'حریم خصوصی'), ('faq', 'سوالات متداول')], max_length=24, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('seo_description', models.CharField(blank=True, max_length=320)),
            ],
            options={
                'verbose_name': 'صفحه استاتیک',
                'verbose_name_plural': 'صفحات استاتیک',
            },
        ),
        migrations.CreateModel(
            name='ThemeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('variant', models.CharField(choices=[('light', 'روشن'), ('dark', 'تیره'), ('mono', 'تک رنگ'), ('accent', 'اکسنت')], default='light', max_length=16)),
                ('file_path', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'دارایی تم',
                'verbose_name_plural': 'دارایی\u200cهای تم',
            },
        ),
    ]
