# Generated by Django 4.2 on 2026-04-10 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.CharField(default='general', max_length=80)),
                ('key', models.SlugField(max_length=160, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('text', models.TextField()),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'متن سایت',
                'verbose_name_plural': 'متن\u200cهای سایت',
                'ordering': ['group', 'title'],
            },
        ),
    ]
