# Generated by Django 4.2 on 2026-04-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_session_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='memory_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='persona_choice',
            field=models.CharField(choices=[('default', 'پیش\u200cفرض'), ('professional', 'حرفه\u200cای'), ('creative', 'خلاق'), ('analyst', 'تحلیل\u200cگر'), ('supportive', 'همراه و دوستانه')], default='default', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
