# Generated by Django 4.2 on 2026-04-10 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('provider_label', models.CharField(max_length=120)),
                ('endpoint_url', models.URLField()),
                ('http_method', models.CharField(default='POST', max_length=10)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('model_identifier', models.CharField(max_length=255)),
                ('timeout_seconds', models.PositiveIntegerField(default=60)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('request_format', models.CharField(choices=[('openai', 'OpenAI Compatible'), ('generic', 'Generic JSON')], default='openai', max_length=20)),
                ('response_text_path', models.CharField(default='choices.0.message.content', max_length=160)),
                ('system_prompt', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('limitations', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'مدل هوش مصنوعی',
                'verbose_name_plural': 'مدل\u200cهای هوش مصنوعی',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_session_key', models.CharField(blank=True, max_length=40)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('is_active', models.BooleanField(default=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversations', to='ai_platform.aimodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'گفتگو',
                'verbose_name_plural': 'گفتگوها',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'کاربر'), ('assistant', 'دستیار'), ('system', 'سیستم')], max_length=12)),
                ('content', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='user_uploads/%Y/%m/%d/')),
                ('attachment_type', models.CharField(blank=True, max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_platform.conversation')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام\u200cها',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIModelCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability_type', models.CharField(choices=[('text', 'متن'), ('image_input', 'ورودی تصویر'), ('file_input', 'ورودی فایل')], max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='ai_platform.aimodel')),
            ],
            options={
                'verbose_name': 'قابلیت مدل',
                'verbose_name_plural': 'قابلیت\u200cهای مدل',
                'unique_together': {('model', 'capability_type')},
            },
        ),
    ]
